use superstore;

# Performing tasks

# 1. Verifing row count

SELECT COUNT(*) AS total_rows 
FROM superstore_campaign;

# 2. Checking Duplicates

SELECT ID, COUNT(*) 
FROM superstore_campaign
GROUP BY ID
HAVING COUNT(*) > 1;

# 3 Check null Values

SELECT 
    COUNT(*) AS missing_income
FROM superstore_campaign
WHERE Income IS NULL;

# 4. Checking Min and Max VALUES

SELECT 
    MIN(Income) AS min_income,
    MAX(Income) AS max_income,
    MIN(Year_Birth) AS min_birth,
    MAX(Year_Birth) AS max_birth,
    MIN(Recency) AS min_recency,
    MAX(Recency) AS max_recency
FROM superstore_campaign;

# 5. Check Total Min/Max Spendings

SELECT 
    MIN(MntWines + MntFruits + MntMeatProducts + 
        MntFishProducts + MntSweetProducts + MntGoldProds) AS min_spend,
        
    MAX(MntWines + MntFruits + MntMeatProducts + 
        MntFishProducts + MntSweetProducts + MntGoldProds) AS max_spend
FROM superstore_campaign;

# 6. Checking Distinct Values

SELECT DISTINCT Education FROM superstore_campaign;

SELECT DISTINCT Marital_Status FROM superstore_campaign;

# 7. Response Distribution

SELECT 
    CASE 
		WHEN response = 1 THEN "YES"
        ELSE "NO"
	END as Response,
    COUNT(*) AS count
FROM superstore_campaign
GROUP BY Response;

# 8. Average income by merital Status

SELECT 
	marital_status,
    round(avg(income)) as Average_Income
FROM superstore_campaign
GROUP BY 1
ORDER BY 2 DESC;

# 9. Count orders of Sale day by day

SELECT 
	dayname(Dt_Customer) as Day_,
    count(*) as Total_Orders
FROM superstore_campaign
GROUP BY Day_
ORDER BY Total_Orders DESC;

# 10. Total Revenue Generated by Education level

SELECT
	Education,
    sum(MntWines) as Wine_Products,
    sum(MntFruits) as Fruits,
    sum(MntMeatProducts) as Meat_Product,
    sum(MntFishProducts) as Fish_Products,
    sum(MntSweetProducts) as Sweet_Products,
    sum(MntGoldProds) as Gold_Prods
FROM superstore_campaign
GROUP BY Education;



SELECT * FROM superstore_campaign;